### PR TITLE
added electric tool parts

### PR DESCRIPTION
**Pull request by Trinsdar**

### CODE REVIEW

**Comment by Vliro** [comment]
Don't you need textures for these?

**Comment by Trinsdar** [comment]
I did add texture

**Comment by Vliro** [comment]
Oh I didnt see. I'll finish up my current recipe work and then perhaps you can add MaterialRecipes for them.

**Comment by Trinsdar** [comment]
should drillbit and such be called drill bit or drill tip?

**Comment by Vliro** [comment]
Are there recipes for them?

**Comment by Trinsdar** [comment]
Not in antimatter, cause the recipes in gt5u require steel for the drill bit,  wrench bit,  and chainsaw bit.  The only one that could have a recipe done in antimatter is the buzzsaw blade, since that one is just plates of the mat and crafting tools

**Comment by Trinsdar** [comment]
I think it's that way in gt6 too

**Comment by Trinsdar** [comment]
Besides,  i think drills and such recipes should be done by the mods themselves,  since a drill has a much more complicated recipe than a pickaxe for example

**Pull request closed without merging**
