### PR TITLE
added material armor

### PR DESCRIPTION
**Pull request by Trinsdar**
Not sure if armor stuff should be separate or added with tools, i would think separate so that for example one could add iron tools but not iron armor since iron armor already exists.
Also this will be marked as draft till i get armor model coloring working

### CODE REVIEW

**Comment by Rongmario** [comment]
Decent PR, I might recommend making a separate class for it instead of being part of `AntimatterToolType` since it ends up inheriting too many useless variables, and armors itself has unique variables that don't apply to other tools too.

**Comment by Trinsdar** [comment]
Yah that sounds like a good idea

**Comment by Vliro** [comment]
Is this ready? Does coloring work?

**Comment by Trinsdar** [comment]
Yes i think it's ready

**Comment by Vliro** [comment]
How did you map materials to armor stats like toughness? Or is that wip

**Comment by Trinsdar** [comment]
Attribute modifiers,  i think they work. Also by the way the specified material armor adds to the default amount,  which is based on iron,  so if a material wants less all they need to do us put in a negative number,  though unfortunately only - 1 would work right now cause of how it's setup, maybe i should do an array for the armor values instead of a single int in Material?

**Pull request merged**
