### PR TITLE
Basic multiblocks

### PR DESCRIPTION
**Pull request by Trinsdar**
I think items are done, and fluids are probably also done, energy though I'm not sure about

### CODE REVIEW

**Comment by Vliro** [comment]
How is this better than MultiblockHandlers that are already implemented? They work fine afaik

**Comment by Trinsdar** [comment]
Because the current handlers don't let multiblocks handle recipes via the gui,  this makes TileEntityBasicMultiMachine able to pricess stuff via what's in rhs gui

**Comment by Vliro** [comment]
Why not just add slots in the multiblock GUI? Multiblocks use the same recipe handler as other machines.

**Comment by Trinsdar** [comment]
I can add slots,  but i don't think recipes can see them,  or at least that's the impression i got from the code. Technically I never actually tested if it works as is right now,  so i'll test it and get back to you.

**Comment by Vliro** [comment]
Take a look at the multi item handler. It shouldnt be too hard to make it include gui slots.

**Comment by Vliro** [comment]
I was working on it but got sidetracked. Shouldnt it be as simple as super.getItems(), which gets all regular machine items? @Trinsdar

**Comment by Trinsdar** [comment]
I'll take a look later once I'm able to get on my computer

**Comment by Trinsdar** [comment]
Going to close this,  cause i'm going to redo it differently

**Pull request closed without merging**
