### PR TITLE
fixed fluid export method crashing with less from tle tanks then to tile tanks and fixed it not exporting from a tile that has more tanks then the to tile

### PR DESCRIPTION
**Pull request by Trinsdar**
also probably in the process prevented a crash that's could've happened if the to tile had more tanks then the from tile

### CODE REVIEW

**Comment by Vliro** [comment]
Should've been fixed already in dev.

**Comment by Trinsdar** [comment]
you only fixed part of it

**Comment by Trinsdar** [comment]
by the way I did confirm just recently that without the j loop it will crash from an index out of bounds exception if the from tile has less tanks then the to tile

**Comment by Vliro** [comment]
I can take a look if you updated it to the dev branch, if there is still an issue

**Pull request merged**
