### PR TITLE
Some refactoring

### PR DESCRIPTION
**Pull request by qubka**
Replace String.join by + (String Builders) where is suitable for improving readability
Replace some "" by '' chars
Replace string builder by the contact where is reasonable

### CODE REVIEW

**Comment by Muramasa-** [comment]
A lot of this is really unnecessary

**Comment by repo-alt** [comment]
concat() is really not more readable than +
otherwise looks harmless and sometimes good cleanup

**Comment by qubka** [comment]
concat is no major changes, mostly I just replaced String.join by String Builder. it's true that it's not a super important changeы, but concat is much more productive than StringBuilder for connecting a pair of strings, so I thought it would be nice if the mod loads a little faster )))

**Comment by Muramasa-** [comment]
I'm going to close this, but happy to consider a PR for splitting Tier into VoltageTier and MachineTier

**Pull request closed without merging**
